services:
  # Service 1: User Service
  user-service:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE_NAME: user-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=user_db
    depends_on:
      - user-db

  user-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db
    volumes:
      - ./services/user-service/ops/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  user-db-data: