services:
  # Service 1: User Service
  userd:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        SERVICE_NAME: userd
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - DB_SSLMODE=disable
    container_name: userd
    depends_on:
      - userd-db
    restart: on-failure

  userd-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db
      - DB_SSLMODE=disable
    volumes:
      - ./services/userd/ops/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - userd-db-data:/var/lib/postgresql/data
    container_name: user-db 
    ports:
      - "5433:5432"

volumes:
  userd-db-data:

networks:
  default: